// Rebuild only when intentionally updating the Natural Earth boundary dataset.
// Usage: node scripts/map-asset.mjs /path/to/ne_50m_admin_0_countries.geojson
import {readFile,writeFile,mkdir} from 'node:fs/promises';
if(!process.argv[2])throw Error('Pass a downloaded Natural Earth 1:50m countries GeoJSON file.');
const source=JSON.parse(await readFile(process.argv[2],'utf8'));
const sa=source.features.find(f=>f.properties.ADM0_A3==='SAU');if(!sa)throw Error('Saudi Arabia missing');
const rings=sa.geometry.type==='MultiPolygon'?sa.geometry.coordinates.flat():sa.geometry.coordinates;
const project=([lon,lat])=>[30+(lon-34)*34*.91,25+(33-lat)*34];
const path=rings.map(r=>r.map((p,i)=>(i?'L':'M')+project(p).map(v=>v.toFixed(2)).join(',')).join(' ')+'Z').join(' ');
await writeFile('src/saudi-outline.ts',`// Natural Earth 1:50m, public domain. Generated by scripts/map-asset.mjs.\nexport const saudiOutline=${JSON.stringify(path)};\nexport const projectCity=(lon:number,lat:number)=>[30+(lon-34)*34*.91,25+(33-lat)*34];\n`);
await mkdir('public/map',{recursive:true});await writeFile('public/map/saudi-arabia.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 630"><title>المملكة العربية السعودية</title><path d="${path}" fill="#087e45" stroke="#94ddb0" stroke-width="2"/></svg>`);
console.log('Generated local Saudi map assets.');
