import {MapExperience} from './MapExperience';
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowUpLeft, BarChart3, Check, ChevronLeft, Download, ExternalLink, Globe2, Maximize2, RefreshCw, Sparkles, Trophy, X, WifiOff, MapPin, ScanLine, Cpu, Users, Plane, Leaf, TrainFront, TrendingUp, Fingerprint, Clock3, MousePointer2, Heart } from 'lucide-react';
import QRCode from 'qrcode';
import { cities, levelNames, type Chart, type RoundView, type Stats } from '../shared/types';
import { api, getRound, getStats, readSession, writeSession } from './api';
import './styles.css';
import './design.css';
import { PersonalCard } from './PersonalCard';
const nf=new Intl.NumberFormat('ar-SA',{maximumFractionDigits:1});
const n=(v:number)=>nf.format(v);
function navigate(path:string){history.pushState(null,'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0});}
function Link({to,children,...props}:{to:string;children:React.ReactNode;className?:string}){return <a href={to} {...props} onClick={e=>{if(!e.ctrlKey&&!e.metaKey){e.preventDefault();navigate(to);}}}>{children}</a>;}
function ErrorBox({message}:{message:string}) {return message?<div className="error" role="alert"><WifiOff size={19}/><span>{message}</span></div>:null;}
function ClubLogo({className=''}:{className?:string}){return <img className={`club-logo ${className}`} src="/brand/data-science-club.jpg" width="64" height="64" alt="شعار نادي علوم البيانات"/>;}
function Logo(){return <Link to="/" className="brand"><ClubLogo/><span><b>نادي علوم البيانات</b><small>جامعة جدة <span aria-hidden="true">/</span> <span lang="en">DATA SCIENCE CLUB</span></small></span></Link>;}
function AnimatedNumber({value}:{value:number}){const [shown,setShown]=useState(0);const previous=useRef(0);useEffect(()=>{const from=previous.current;previous.current=value;if(matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(value);return;}let frame=0;const started=performance.now();const tick=(time:number)=>{const t=Math.min((time-started)/800,1);setShown(from+(value-from)*(1-Math.pow(1-t,3)));if(t<1)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);return <>{n(Math.round(shown))}</>;}
function DataStage(){return <div className="data-stage" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><span className="orbit-point point-one"/><span className="orbit-point point-two"/><span className="orbit-point point-three"/><div className="stage-label"><span className="mini-dot"/> رحلة اكتشاف بالأرقام</div><div className="data-core"><span className="core-caption">ثلاثة أسئلة</span><b>٣</b><span className="core-bottom">وهنا تبدأ الحكاية</span><div className="core-ticks">{Array.from({length:32},(_,i)=><i key={i} style={{transform:`rotate(${i*11.25}deg)`}}/>)}</div></div><div className="floating-data floating-top"><span className="float-icon"><BarChart3 size={21}/></span><div><small>اقرأ. لاحظ. اكتشف.</small><div className="mini-chart">{[35,62,44,80,61,95,76].map((h,i)=><i key={i} style={{height:`${h}%`,animationDelay:`${i*80}ms`}}/>)}</div></div></div><div className="floating-data floating-bottom"><span className="float-icon gold"><Trophy size={23}/></span><div><small>إنجازك له تذكار</small><b>بطاقتك بانتظارك</b></div><Sparkles className="tiny-spark" size={17}/></div><div className="stage-foot"><span>توقّع</span><i/><span>اكتشف</span><i/><span>تعلّم</span></div></div>;}
function ChartView({chart}:{chart:Chart}){const max=Math.max(...chart.values.map(x=>x.value),1);return <figure className="chart"><figcaption>{chart.title}<small>{chart.unit} · المقياس يبدأ من الصفر</small></figcaption><div className="bars">{chart.values.map((x,i)=><div className="bar-row" key={x.label}><div className="bar-label"><span>{x.label}</span><b>{n(x.value)}</b></div><div className="bar-track"><div className={`bar-fill tone-${i%3}`} style={{width:`${x.value/max*100}%`}}/></div></div>)}</div>{chart.note&&<p className="chart-note">{chart.note}</p>}</figure>;}
function useStats(interval:number){const [data,setData]=useState<Stats|null>(null);const [error,setError]=useState('');useEffect(()=>{let active=true;let busy=false;async function refresh(){if(document.hidden||busy)return;busy=true;try{const value=await getStats();if(active){setData(value);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{busy=false;}}void refresh();const timer=setInterval(()=>void refresh(),interval);document.addEventListener('visibilitychange',refresh);return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[interval]);return{data,error};}
function Home({begin,busy,error,resume}:{begin:()=>void;busy:boolean;error:string;resume:boolean}) {
  const {data}=useStats(30000);
  const topics=[{name:'تقنية',icon:Cpu},{name:'مجتمع',icon:Users},{name:'سياحة',icon:Plane},{name:'بيئة',icon:Leaf},{name:'نقل',icon:TrainFront},{name:'اقتصاد',icon:TrendingUp}];
  return <main className="home-v2 wrap"><section className="hero-shell"><div className="hero-grid"/><div className="hero-copy"><div className="national-label"><Sparkles size={16}/><span>نحتفي بوطننا… بطريقتنا</span><span className="year-label">٢٠٢٦</span></div><p className="hero-kicker">تحدّي اليوم الوطني السعودي</p><h1>السعودية<br/><em>بالأرقام<span className="title-dot">.</span></em></h1><p className="hero-description">وراء كل رقم حكاية عن وطننا.<br/>خمّنها، اكتشفها، وخلّ معرفتك بالسعودية تكبر.</p><div className="hero-actions"><button className="button hero-start" onClick={begin} disabled={busy}>{busy?<RefreshCw className="spin" size={20}/>:<MousePointer2 size={20}/>}<span>{busy?'نجهّز جولتك…':resume?'كمّل جولتك':'يلا، نكتشف الأرقام'}</span><ArrowLeft size={22}/></button><Link to="/results" className="hero-results">شوف النتائج <ArrowUpLeft size={18}/></Link></div><div className="hero-reassurance"><span><Clock3 size={16}/> دقيقتان تقريبًا</span><span><Fingerprint size={16}/> بدون تسجيل</span></div><ErrorBox message={error}/></div><DataStage/><div className="hero-bottom"><span><Heart size={16}/> وطن نعرفه… ووطن نكتشفه</span><Link to="/results" className="participant-count"><span className="live-dot"/>{data?<><b><AnimatedNumber value={data.completed}/></b> مشاركة مكتملة</>:'اكتشف تفاعل المشاركين'}<ChevronLeft size={17}/></Link></div></section><section className="discovery-row" aria-label="خطوات التجربة"><div className="discovery-intro"><span className="eyebrow">رحلة قصيرة، معرفة تبقى</span><h2>من توقّع… إلى اكتشاف.</h2></div><div className="journey-step"><span className="journey-number">٠١</span><div><h3>توقّع الرقم</h3><p>ابدأ بسؤال يفتح فضولك.</p></div></div><div className="journey-step"><span className="journey-number">٠٢</span><div><h3>اقرأ الحكاية</h3><p>تعلّم من الإجابة ومصدرها.</p></div></div><div className="journey-step"><span className="journey-number">٠٣</span><div><h3>خذ تذكارك</h3><p>بطاقة تحمل لقبك وإنجازك.</p></div></div></section><section className="topic-strip-v2" aria-label="مجالات التحدي"><span>ست زوايا لاكتشاف المملكة</span><div>{topics.map(({name,icon:Icon})=><span className="topic-item" key={name}><Icon size={18}/>{name}</span>)}</div><small>١٨ سؤالًا · ٣ مستويات</small></section></main>;
}
function Quiz({round,onAnswer,onNext,index,selected,setSelected,busy,error,reload}:{round:RoundView;onAnswer:()=>void;onNext:()=>void;index:number;selected:number|null;setSelected:(v:number)=>void;busy:boolean;error:string;reload:()=>void}){
  const q=round.questions[index];const answer=round.answers.find(a=>a.questionId===q.id);
  return <main className="quiz wrap narrow"><div className="quiz-meta"><Link to="/">الرئيسية</Link><span>السؤال {n(index+1)} من ٣</span></div><div className="progress" aria-label={`السؤال ${index+1} من 3`}>{[0,1,2].map(i=><span key={i} className={i<=index?'active':''}/>)}</div><section className="question-panel" key={q.id}><div className="question-tags"><span>{levelNames[q.level]}</span><span>{q.topic}</span><small>بيانات {q.year}</small></div>{q.chart?<ChartView chart={q.chart}/>:<div className="headline-number" dir="ltr">{q.headline}</div>}<h1 tabIndex={-1}>{q.prompt}</h1><div className="options" role="group" aria-label="خيارات الإجابة">{q.options.map((option,i)=><button key={option} className={`option ${selected===i?'selected':''} ${answer&&answer.correct===i?'correct':''} ${answer&&answer.selected===i&&!answer.isCorrect?'wrong':''}`} aria-pressed={selected===i} disabled={!!answer||busy} onClick={()=>setSelected(i)}><span className="option-letter">{['أ','ب','ج'][i]}</span><span>{option}</span>{answer&&answer.correct===i?<Check size={20}/>:answer&&answer.selected===i?<X size={20}/>:<span className="radio"/>}</button>)}</div><ErrorBox message={error}/>{error&&<button className="text-button" onClick={reload}>استرجاع الإجابة المحفوظة</button>}
      {answer?<section className={`feedback ${answer.isCorrect?'success':''}`} aria-live="polite"><div><span className="feedback-symbol">{answer.isCorrect?<Check size={22}/>:<Sparkles size={22}/>}</span><h2>{answer.isCorrect?'توقّعك في مكانه!':'معلومة جديدة لرصيدك'}</h2></div><p>{answer.explanation}</p><p className="lesson"><BarChart3 size={18}/>{answer.lesson}</p><a href={q.source.url} target="_blank" rel="noreferrer">{q.source.name}<ExternalLink size={14}/></a></section>:<p className="muted small">اختر إجابة ثم أكّدها؛ بعدها نكشف لك المعلومة ومصدرها.</p>}
      <button className="button green" disabled={busy||(!answer&&selected===null)} onClick={answer?onNext:onAnswer}>{busy?'جارٍ حفظ إجابتك…':answer?(index===2?'شوف نتيجتك':'السؤال التالي'):'تأكيد الإجابة'}<ArrowLeft size={21}/></button>
    </section></main>;
}
function Result({round,vote,busy,error,newRound}:{round:RoundView;vote:(city:string)=>void;busy:boolean;error:string;newRound:()=>void}) {
  const [choice,setChoice]=useState(round.vote||readSession('poll-choice')||'');
  return <main className="wrap result-layout personalized-result"><section className="result-copy"><div className="eyebrow">ثلاثة أسئلة، ومعرفة أكثر</div><h1>اكتشافك يستحق <em>تحتفظ فيه.</em></h1><p className="lead">{round.title}، هذه بطاقتك. تصميم خاص بإنجازك، ولمستك تكملها.</p></section><PersonalCard round={round}/><div className="result-actions"><Link to="/results">شوف النتائج العامة <ArrowUpLeft size={17}/></Link><button onClick={newRound} className="text-button" disabled={busy}>جولة جديدة <RefreshCw size={16}/></button></div>
    <section className="poll-panel"><div><span className="eyebrow">بيانات المشاركين</span><h2>أي وجهة سعودية تتمنى تزورها؟</h2><p>صوتك يصير جزءًا من الرسم. المشاركة اختيارية.</p></div><div className="poll-body">{round.vote?<div className="vote-success" role="status"><Check/><span>سجّلنا اختيارك: <b>{round.vote}</b><small>تابع النتائج وشوف كيف تتكوّن الصورة مع كل مشاركة.</small></span><Link to="/results">شوف الرسم <ArrowLeft size={18}/></Link></div>:<><div className="city-options" role="group" aria-label="اختر وجهة">{cities.map(city=><button className={choice===city?'chosen':''} key={city} aria-pressed={choice===city} disabled={busy} onClick={()=>{setChoice(city);writeSession('poll-choice',city);}}><MapPin size={16}/>{city}</button>)}</div><button className="button green" disabled={!choice||busy} onClick={()=>vote(choice)}>{busy?'نحفظ صوتك…':'أضف صوتك'}<ArrowLeft size={18}/></button></>}<ErrorBox message={error}/></div></section></main>;
}
function Results(){const display=new URLSearchParams(location.search).get('display')==='1';const{data,error}=useStats(display?5000:30000);const[qr,setQr]=useState('');const[details,setDetails]=useState('');useEffect(()=>{if(display)void QRCode.toDataURL(location.origin,{width:200,margin:1}).then(setQr);},[display]);
  if(!data)return <main className="wrap loading"><BarChart3 size={38}/><h1>نقرأ الصورة من البيانات…</h1><ErrorBox message={error}/></main>;
  const totalVotes=data.votes.reduce((sum,v)=>sum+v.count,0);const answered=data.questions.reduce((s,q)=>s+q.total,0);const correct=data.questions.reduce((s,q)=>s+q.correct,0);const observed=data.questions.filter(q=>q.total>=5).sort((a,b)=>a.correct/a.total-b.correct/b.total);const selectedQuestion=data.questions.find(q=>q.id===details);const leader=[...data.votes].sort((a,b)=>b.count-a.count);const tied=leader.filter(x=>x.count===leader[0].count);
  return <main className={`wrap dashboard ${display?'display-mode':''}`}><div className="dashboard-heading"><div><div className="eyebrow">النتائج العامة</div><h1>الصورة تكبر <em>بمشاركتكم.</em></h1><p>إجابات وتوقّعات تتحول إلى بيانات نفهمها معًا.</p></div><div className="live-tools"><span className={`live-pill ${error?'stale':''}`}><span/>{error?'تعذّر التحديث':'تحديث تلقائي'}</span><small>آخر تحديث {new Date(data.updatedAt).toLocaleTimeString('ar-SA')}</small><button className="text-button" onClick={()=>{navigate(display?'/results':'/results?display=1');if(!display)void document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)void document.exitFullscreen();}}><Maximize2 size={17}/>{display?'إنهاء وضع الشاشة':'عرض شاشة البوث'}</button></div></div>{display&&<button className="text-button" onClick={()=>void document.documentElement.requestFullscreen?.().catch(()=>{})}>ملء الشاشة</button>}<ErrorBox message={error}/>{data.environment!=='production'&&<div className="test-banner">بيئة تجريبية — هذه المشاركات لا تدخل في بيانات الفعالية</div>}
      <div className="metrics"><article><span>مشاركة مكتملة</span><b><AnimatedNumber value={data.completed}/></b><small>كل جولة مكتملة تُحسب مشاركة</small></article><article><span>متوسط النتيجة</span><b>{data.completed?n(data.scoreSum/data.completed):'—'}<small> / ٣</small></b><small>للمشاركات المكتملة</small></article><article><span>الإجابات الصحيحة</span><b>{answered?`${n(correct/answered*100)}٪`:'—'}</b><small>من جميع الإجابات المؤكّدة</small></article><article><span>خبراء البيانات</span><b><AnimatedNumber value={data.distribution[3]}/></b><small>حققوا ٣ من ٣</small></article></div>
      <div className="dashboard-grid"><section className="data-panel poll-chart"><div className="panel-heading"><div><span className="eyebrow">بيانات المشاركين</span><h2>وجهتنا القادمة</h2></div><span className="count-chip">{n(totalVotes)} صوت</span></div><p>أي وجهة سعودية تتمنى تزورها؟</p><ChartView chart={{title:'اختيارات الوجهات',unit:'صوت',values:data.votes.map(v=>({label:v.label,value:v.count}))}}/><div className="insight"><Sparkles size={19}/><p>{totalVotes===0?'أول صوت يرسم بداية الصورة.':tied.length>1?'أكثر من وجهة تتشارك الصدارة حاليًا.':`${leader[0].label} تتصدر الاختيارات بنسبة ${n(leader[0].count/totalVotes*100)}٪ من الأصوات.`}<small>هذه اختيارات المشاركين، ولا تمثّل جميع سكان المملكة أو طلاب الجامعة.</small></p></div></section>
      <section className="data-panel"><div className="panel-heading"><div><span className="eyebrow">كيف كانت التجربة؟</span><h2>توزيع الدرجات</h2></div><Trophy size={23}/></div><div className="score-bars">{data.distribution.map((v,i)=><div key={i}><b>{n(v)}</b><div className="score-bar-track"><div style={{height:`${data.completed&&v?Math.max(2,v/Math.max(...data.distribution,1)*100):0}%`}}/></div><span>{n(i)} / ٣</span></div>)}</div><div className="insight"><BarChart3 size={19}/><p>{data.completed?`${n(data.distribution[3]/data.completed*100)}٪ من الجولات انتهت بالدرجة الكاملة.`:'كل مشاركة جديدة تضيف جزءًا إلى الرسم.'}<small>قد يشارك الشخص أكثر من مرة، والأسئلة تتنوع بين الجولات.</small></p></div><div className="hardest"><span>السؤال الأكثر تحدّيًا حاليًا</span>{observed.length?<><b>{observed[0].topic} · {observed[0].id}</b><p>{observed[0].prompt}</p><small>{n(observed[0].correct/observed[0].total*100)}٪ إجابات صحيحة من {n(observed[0].total)} إجابة</small></>:<p>يظهر بعد جمع خمس إجابات على الأقل لأحد الأسئلة.</p>}</div></section></div>
      {display?<section className="join-strip">{qr&&<img src={qr} width="100" height="100" alt="رمز QR لبدء التحدي"/>}<div><h2>خلّ رقمك جزءًا من الحكاية.</h2><p>امسح الرمز · أجب عن ثلاثة أسئلة · حمّل بطاقتك</p></div><span className="site-url" dir="ltr">{location.host}</span></section>:<section className="data-panel question-breakdown"><h2>وراء كل إجابة، توقّع</h2><p>استكشف توزيع اختيارات المشاركين. قد تعطيك النتائج تلميحًا إذا لم تبدأ التحدي بعد.</p><label htmlFor="question-details">اختر سؤالًا</label><select id="question-details" value={details} onChange={e=>setDetails(e.target.value)}><option value="">عرض توزيع الاختيارات…</option>{data.questions.map(q=><option key={q.id} value={q.id}>{q.topic} · {q.id} — {q.prompt}</option>)}</select>{selectedQuestion&&<><p>{selectedQuestion.total?`${n(selectedQuestion.correct/selectedQuestion.total*100)}٪ إجابات صحيحة من ${n(selectedQuestion.total)} إجابة`:'لا توجد إجابات لهذا السؤال بعد.'}</p><ChartView chart={{title:selectedQuestion.prompt,unit:'إجابة',values:selectedQuestion.choices.map(c=>({label:c.label,value:c.count}))}}/></>}</section>}
    </main>;
}
function App(){const[path,setPath]=useState(location.pathname+location.search);const[key,setKey]=useState(readSession('round-key')||'');const[round,setRound]=useState<RoundView|null>(null);const[index,setIndex]=useState(0);const[selected,setSelected]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[online,setOnline]=useState(navigator.onLine);const headingRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const route=()=>{setPath(location.pathname+location.search);setError('');};const net=()=>setOnline(navigator.onLine);window.addEventListener('popstate',route);window.addEventListener('online',net);window.addEventListener('offline',net);return()=>{window.removeEventListener('popstate',route);window.removeEventListener('online',net);window.removeEventListener('offline',net);};},[]);
  useEffect(()=>{document.title=`${path.startsWith('/results')?'النتائج | ':path==='/quiz'?'التحدي | ':path==='/result'?'بطاقتك | ':''}السعودية بالأرقام`;headingRef.current?.focus();},[path]);
  function choice(value:number){setSelected(value);if(round)writeSession(`choice-${key}-${round.questions[index].id}`,String(value));}
  async function begin(fresh=false){setBusy(true);setError('');let token=fresh?'':key;if(!token){token=crypto.randomUUID();writeSession('round-key',token);writeSession('poll-choice','');setKey(token);}try{const value=await api<RoundView>('round',{method:'POST',key:token});setRound(value);setIndex(Math.min(value.answers.length,2));const saved=readSession(`choice-${token}-${value.questions[Math.min(value.answers.length,2)].id}`);setSelected(saved===null?null:Number(saved));navigate(value.completed?'/result':'/quiz');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function restore(){if(!key){navigate('/');return;}setBusy(true);setError('');try{const value=await getRound(key);setRound(value);setIndex(Math.min(value.answers.length,2));const saved=readSession(`choice-${key}-${value.questions[Math.min(value.answers.length,2)].id}`);setSelected(saved===null?null:Number(saved));navigate(value.completed?'/result':'/quiz');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{if((path==='/quiz'||path==='/result')&&!round)void restore();},[path]);
  async function answer(){if(!round||selected===null)return;setBusy(true);setError('');try{setRound(await api<RoundView>('answer',{method:'POST',key,body:{questionId:round.questions[index].id,selected}}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function vote(city:string){setBusy(true);setError('');try{setRound(await api<RoundView>('vote',{method:'POST',key,body:{city}}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function next(){if(index===2){navigate('/result');return;}setIndex(index+1);const saved=round?readSession(`choice-${key}-${round.questions[index+1].id}`):null;setSelected(saved===null?null:Number(saved));setError('');window.scrollTo({top:0});}
  const display=path.includes('display=1');
  return <><header className="site-header wrap"><Logo/><nav aria-label="التنقل الرئيسي"><Link to="/" className={!path.startsWith('/results')?'active':''}>التحدّي</Link><Link to="/results" className={path.startsWith('/results')?'active':''}>النتائج <BarChart3 size={17}/></Link></nav><span className="header-note"><span className="header-edition">JDSC <i/> 2026</span><small>وطن نكتشفه بالأرقام</small></span></header><div ref={headingRef} tabIndex={-1} className="focus-anchor"/>{!online&&<div className="offline" role="status"><WifiOff size={17}/>أنت غير متصل. احتفظ بالصفحة وأعد المحاولة بعد عودة الإنترنت.</div>}{round?.environment==='staging'&&!path.startsWith('/results')&&<div className="test-banner wrap">نسخة تجريبية — البيانات منفصلة عن الفعالية</div>}
    {path==='/legacy-results'?<Results/>:path!=='/quiz'&&path!=='/result'?<MapExperience path={path} navigate={navigate}/>:path==='/quiz'&&round?<Quiz round={round} index={index} selected={selected} setSelected={choice} onAnswer={()=>void answer()} onNext={next} busy={busy} error={error} reload={()=>void restore()}/>:path==='/result'&&round?.completed?<Result round={round} vote={city=>void vote(city)} busy={busy} error={error} newRound={()=>void begin(true)}/>:path==='/quiz'||path==='/result'?<main className="wrap loading"><h1>نسترجع جولتك…</h1><ErrorBox message={error}/>{error&&<><button className="button green" onClick={()=>void restore()}>إعادة المحاولة</button><button className="text-button" onClick={()=>void begin(true)}>بدء جولة جديدة</button></>}</main>:<Home begin={()=>void begin()} busy={busy} error={error} resume={!!key}/>}
    {!display&&<footer className="wrap"><div className="footer-brand"><ClubLogo/><span>السعودية بالأرقام<small>نادي علوم البيانات · جامعة جدة</small></span></div><span className="privacy-note"><Fingerprint size={17}/> مشاركتك بدون تسجيل أو بريد.</span><span className="footer-signature">صُنع بفضول، وحبّ للوطن <Heart size={15}/></span></footer>}</>;
}
createRoot(document.getElementById('root')!).render(<App/>);





